In [2]:
import pandas as pd
import json
import os

In [2]:
def parse_json(json_file):
    with open(json_file, 'r') as f:
        data = json.load(f)

    prices_data = data['prices']

    df = pd.DataFrame(prices_data, columns=['date', 'price', 'quantity'])

    df['date'] = pd.to_datetime(df['date'], format='%b %d %Y %H: +%f')
    df['hash_name'] = json_file[:-5]

    return df

# Creating Dataframe of all json files

In [3]:
path_to_json = 'Jsons/'

In [4]:
# Initialize a list to store JSON file paths
json_files = []

# Recursively search for JSON files within the JSON directory
for root, dirs, files in os.walk(os.path.join(path_to_json)):
    for file in files:
        if file.endswith('.json'):
            json_files.append(os.path.join(root, file))

# Print the list of JSON file paths
for file in json_files:
    if "ipynb" in file:
        print(file)
        
print(json_files[:5])

['Jsons/crate_json/Antwerp 2022 Challengers Sticker Capsule.json', 'Jsons/crate_json/Autograph Capsule | Team Liquid | MLG Columbus 2016.json', 'Jsons/crate_json/CS:GO Patch Pack.json', 'Jsons/crate_json/Copenhagen 2024 Anubis Souvenir Package.json', 'Jsons/crate_json/Stockholm 2021 Finalists Autograph Capsule.json']

In [5]:
all_data = pd.DataFrame()

for file in json_files:
    df = parse_json(file)
    all_data = pd.concat([all_data, df], ignore_index=True)

# all_data = all_data.sort_values(by='date')

all_data.reset_index(drop=True, inplace=True)

all_data

/var/folders/7b/gct8p47933z9hsc7_z71khjh0000gn/T/ipykernel_53019/175423800.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat([all_data, df], ignore_index=True)
/var/folders/7b/gct8p47933z9hsc7_z71khjh0000gn/T/ipykernel_53019/175423800.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat([all_data, df], ignore_index=True)
/var/folders/7b/gct8p47933z9hsc7_z71khjh0000gn/T/ipykernel_53019/175423800.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat([all_data, df], ignore_index=True)

,date,price,quantity,hash_name
0,2022-05-11 01:00:00,0.999,593,Jsons/crate_json/Antwerp 2022 Challengers Stic...
1,2022-05-12 01:00:00,0.979,1281,Jsons/crate_json/Antwerp 2022 Challengers Stic...
2,2022-05-13 01:00:00,0.988,1547,Jsons/crate_json/Antwerp 2022 Challengers Stic...
3,2022-05-14 01:00:00,0.993,1258,Jsons/crate_json/Antwerp 2022 Challengers Stic...
4,2022-05-15 01:00:00,0.992,1603,Jsons/crate_json/Antwerp 2022 Challengers Stic...
...,...,...,...,...
28374307,2024-03-25 14:00:00,0.030,1,Jsons/sticker_json/Sticker | aliStair | Rio 2022
28374308,2024-03-25 15:00:00,0.030,1,Jsons/sticker_json/Sticker | aliStair | Rio 2022
28374309,2024-03-25 20:00:00,0.030,1,Jsons/sticker_json/Sticker | aliStair | Rio 2022
28374310,2024-03-25 22:00:00,0.030,3,Jsons/sticker_json/Sticker | aliStair | Rio 2022
28374311,2024-03-26 02:00:00,0.030,7,Jsons/sticker_json/Sticker | aliStair | Rio 2022

In [6]:
all_data.to_csv('Datasets/all_data.csv', index = False)

In [3]:
all_data = pd.read_csv('Datasets/all_data.csv')

In [4]:
all_data.hash_name[0].split('/')[2]

'Antwerp 2022 Challengers Sticker Capsule'

In [5]:
all_data.hash_name = all_data.hash_name.apply(lambda x : x.split('/')[2])

all_data

,date,price,quantity,hash_name
0,2022-05-11 01:00:00,0.999,593,Antwerp 2022 Challengers Sticker Capsule
1,2022-05-12 01:00:00,0.979,1281,Antwerp 2022 Challengers Sticker Capsule
2,2022-05-13 01:00:00,0.988,1547,Antwerp 2022 Challengers Sticker Capsule
3,2022-05-14 01:00:00,0.993,1258,Antwerp 2022 Challengers Sticker Capsule
4,2022-05-15 01:00:00,0.992,1603,Antwerp 2022 Challengers Sticker Capsule
...,...,...,...,...
28374307,2024-03-25 14:00:00,0.030,1,Sticker | aliStair | Rio 2022
28374308,2024-03-25 15:00:00,0.030,1,Sticker | aliStair | Rio 2022
28374309,2024-03-25 20:00:00,0.030,1,Sticker | aliStair | Rio 2022
28374310,2024-03-25 22:00:00,0.030,3,Sticker | aliStair | Rio 2022
28374311,2024-03-26 02:00:00,0.030,7,Sticker | aliStair | Rio 2022

In [21]:
all_data.date.unique()

<DatetimeArray>
['2022-05-11 01:00:00', '2022-05-12 01:00:00', '2022-05-13 01:00:00',
 '2022-05-14 01:00:00', '2022-05-15 01:00:00', '2022-05-16 01:00:00',
 '2022-05-17 01:00:00', '2022-05-18 01:00:00', '2022-05-19 01:00:00',
 '2022-05-20 01:00:00',
 ...
 '2024-02-20 16:00:00', '2024-02-20 17:00:00', '2024-02-20 18:00:00',
 '2024-02-20 19:00:00', '2024-02-20 20:00:00', '2024-02-20 21:00:00',
 '2024-02-19 02:00:00', '2024-02-19 06:00:00', '2024-02-20 04:00:00',
 '2013-08-13 01:00:00']
Length: 4764, dtype: datetime64[ns]

In [22]:
len(all_data.hash_name.unique())

16328

In [11]:
all_data['date'] = pd.to_datetime(all_data['date'])

pivot_df = all_data.pivot(index='date', columns='hash_name', values='price').reset_index()

pivot_df

hash_name,date,'Blueberries' Buckshot | NSWC SEAL,'Medium Rare' Crasswater | Guerrilla Warfare,'The Doctor' Romanov | Sabre,'Two Times' McCoy | TACP Cavalry,'Two Times' McCoy | USAF TACP,10 Year Birthday Sticker Capsule,1st Lieutenant Farlow | SWAT,2020 RMR Challengers,2020 RMR Contenders,...,â˜… Ursus Knife | Ultraviolet (Battle-Scarred),â˜… Ursus Knife | Ultraviolet (Factory New),â˜… Ursus Knife | Ultraviolet (Field-Tested),â˜… Ursus Knife | Ultraviolet (Minimal Wear),â˜… Ursus Knife | Ultraviolet (Well-Worn),â˜… Ursus Knife | Urban Masked (Battle-Scarred),â˜… Ursus Knife | Urban Masked (Factory New),â˜… Ursus Knife | Urban Masked (Field-Tested),â˜… Ursus Knife | Urban Masked (Minimal Wear),â˜… Ursus Knife | Urban Masked (Well-Worn)
0,2013-08-13 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-08-14 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-08-15 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-08-16 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-08-17 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4759,2024-03-26 15:00:00,9.550,17.325,7.397,4.172,4.050,0.980,5.809,0.270,0.324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4760,2024-03-26 16:00:00,9.138,17.176,7.424,4.120,4.030,0.993,5.763,0.269,0.324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4761,2024-03-26 17:00:00,9.436,NaN,7.380,4.178,3.714,1.007,6.001,0.267,0.320,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4762,2024-03-26 18:00:00,9.603,17.192,7.255,4.093,3.768,0.997,6.049,0.240,0.299,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4763,2024-03-26 19:00:00,9.220,17.840,7.342,4.260,3.808,0.997,5.799,0.269,0.290,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pivot_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4764 entries, 0 to 4763
Columns: 16329 entries, date to â˜… Ursus Knife | Urban Masked (Well-Worn)
dtypes: datetime64[ns](1), float64(16328)
memory usage: 593.5 MB

In [9]:
pivot_df.describe()

hash_name,date,'Blueberries' Buckshot | NSWC SEAL,'Medium Rare' Crasswater | Guerrilla Warfare,'The Doctor' Romanov | Sabre,'Two Times' McCoy | TACP Cavalry,'Two Times' McCoy | USAF TACP,10 Year Birthday Sticker Capsule,1st Lieutenant Farlow | SWAT,2020 RMR Challengers,2020 RMR Contenders,...,â˜… Ursus Knife | Ultraviolet (Battle-Scarred),â˜… Ursus Knife | Ultraviolet (Factory New),â˜… Ursus Knife | Ultraviolet (Field-Tested),â˜… Ursus Knife | Ultraviolet (Minimal Wear),â˜… Ursus Knife | Ultraviolet (Well-Worn),â˜… Ursus Knife | Urban Masked (Battle-Scarred),â˜… Ursus Knife | Urban Masked (Factory New),â˜… Ursus Knife | Urban Masked (Field-Tested),â˜… Ursus Knife | Urban Masked (Minimal Wear),â˜… Ursus Knife | Urban Masked (Well-Worn)
count,4764,1798.000000,1443.000000,2254.000000,1871.000000,2256.000000,1226.000000,1865.000000,1813.000000,1813.000000,...,1269.000000,21.000000,1761.000000,1015.000000,843.000000,1181.000000,34.000000,1936.000000,956.000000,823.000000
mean,2019-11-25 19:37:28.110831360,5.563544,12.697267,5.500861,2.627363,2.406926,1.025736,4.162962,0.292293,0.323955,...,132.570463,586.467524,177.617683,254.194549,159.953912,100.619678,241.773588,115.262665,140.505583,111.539265
min,2013-08-13 01:00:00,0.840000,4.311000,1.976000,0.627000,0.666000,0.762000,1.093000,0.141000,0.136000,...,11.880000,263.530000,82.813000,26.311000,1.350000,55.630000,110.009000,55.881000,82.743000,16.830000
25%,2016-11-15 19:00:00,1.722000,6.706000,3.291000,1.159500,1.157750,0.986000,2.181000,0.196000,0.196000,...,112.821000,516.841000,150.832000,207.480000,134.957500,87.958000,171.417500,99.469750,118.737500,94.629500
50%,2020-02-19 13:00:00,5.063000,15.266000,5.568000,2.500000,2.098000,1.026000,4.879000,0.273000,0.319000,...,124.545000,589.549000,167.097000,238.495000,150.154000,95.818000,236.906000,108.796000,130.207000,106.097000
75%,2023-05-25 07:00:00,9.485250,16.874500,7.278750,4.115000,3.905250,1.071500,5.926000,0.300000,0.349000,...,147.670000,650.000000,202.047000,295.201000,176.163000,106.390000,287.023250,120.235250,150.763000,118.927500
max,2024-03-26 19:00:00,13.649000,21.981000,18.988000,4.901000,5.006000,1.398000,8.070000,1.093000,1.097000,...,536.505000,873.920000,319.997000,555.827000,300.308000,188.660000,405.723000,212.990000,317.735000,215.472000
std,NaN,3.771032,4.994014,2.185433,1.418352,1.300341,0.077248,1.867290,0.165322,0.169950,...,30.711850,141.626313,37.715848,63.602542,37.516666,20.878072,83.173636,25.088348,34.044922,25.684484

In [24]:
pivot_df.to_csv('Datasets/time_series_df.csv',index = False)